# lack these keys
#[derive(Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Debug)]
#matches!(self, DocContent::File { .. })
#false

[color-theme]
name = "Jetbrains Light"

[color-theme.base]
black = "#383A42"
blue = "#4078F2"
current-background = "#d5d5d5"
cyan = "#0184BC"
dim-text = "#A0A1A7"
green = "#50A14F"
grey = "#E5E5E6"
magenta = "#A626A4"
orange = "#D19A66"
primary-background = "$white"
purple = "#A626A4"
red = "#E45649"
secondary-background = "#f2f2f2"
text = "$black"
white = "#ffffff"
yellow = "#C18401"

[color-theme.syntax]
attribute = "$yellow"
"bracket.color.1" = "$blue"
"bracket.color.2" = "$yellow"
"bracket.color.3" = "$purple"
"bracket.unpaired" = "$red"
builtinType = "#123fb8"
comment = "$dim-text"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$text"
enum-member = "$red"
enumMember = "#9211a7"
escape = "$cyan"
field = "$red"
function = "#3d6c7e"
"function.method" = "$blue"
interface = "$text"
keyword = "#073cb7"
"markup.bold" = "$orange"
"markup.heading" = "$red"
"markup.italic" = "$orange"
"markup.link.label" = "$purple"
"markup.link.text" = "$purple"
"markup.link.url" = "$blue"
"markup.list" = "$orange"
method = "$blue"
number = "$yellow"
property = "#881696"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$text"
structure = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$text"
"type.builtin" = "$cyan"
typeAlias = "$text"
variable = "$text"
"variable.other.member" = "$red"

[color-theme.ui]
"activity.background" = "$secondary-background"
"activity.current" = "$primary-background"
"completion.background" = "$secondary-background"
"completion.current" = "$current-background"
"completion_lens.foreground" = "$dim-text"
"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "#E4564966"
"editor.background" = "$primary-background"
"editor.caret" = "#526FFF"
"editor.current_line" = "#fcfaed"
"editor.debug_break_line" = "#528bFF55"
"editor.dim" = "$dim-text"
"editor.drag_drop_background" = "#79c1fc33"
"editor.drag_drop_tab_background" = "#0b0e1433"
"editor.focus" = "#000000"
"editor.foreground" = "$text"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$primary-background"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E06C7515"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#A0A1A720"
"error_lens.other.foreground" = "$dim-text"
"error_lens.warning.background" = "#E5C07B10"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "$secondary-background"
"inlay_hint.background" = "#f5f5f5"
"inlay_hint.foreground" = "#6c7680"
"lapce.border" = "#B4B4B4"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$white"
"lapce.dropdown_shadow" = "#B4B4B4"
"lapce.error" = "#E51400"
"lapce.icon.active" = "$text"
"lapce.icon.inactive" = "$dim-text"
"lapce.plugin.author" = "#707070"
"lapce.plugin.description" = "$text"
"lapce.plugin.name" = "#444444"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.icon" = "$white"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "#B4B4B4BB"
"lapce.tab.active.background" = "$primary-background"
"lapce.tab.active.foreground" = "$text"
"lapce.tab.active.underline" = "#528BFF"
"lapce.tab.inactive.background" = "#EAEAEB"
"lapce.tab.inactive.foreground" = "$text"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.tab.separator" = "#B4B4B4"
"lapce.warn" = "#E9A700"
"markdown.blockquote" = "#686868"
"palette.background" = "$secondary-background"
"palette.current.background" = "$current-background"
"palette.current.foreground" = "$text"
"palette.foreground" = "$text"
"panel.background" = "$secondary-background"
"panel.current.background" = "$current-background"
"panel.current.foreground" = "$text"
"panel.current.foreground.dim" = "$dim-text"
"panel.foreground" = "$text"
"panel.foreground.dim" = "$dim-text"
"panel.hovered.active.background" = "$dim-text"
"panel.hovered.background" = "#CBCBCB"
"panel.hovered.foreground" = "$text"
"panel.hovered.foreground.dim" = "$dim-text"
"source_control.added" = "#50A14FCC"
"source_control.modified" = "#0184BCCC"
"source_control.removed" = "#FF5266CC"
"status.background" = "$secondary-background"
"status.foreground" = "$text"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$white"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$white"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$white"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$white"
"terminal.background" = "$primary-background"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#A0A1A7"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#090A0B"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$text"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$text"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"
"tooltip.background" = "$primary-background"
"tooltip.foreground" = "$text"

[ui]
drop-shadow-width = 0
font-family = ""
font-size = 13
header-height = 35
hover-font-family = ""
hover-font-size = 0
icon-size = 0
list-line-height = 25
open-editors-visible = true
palette-width = 500
scale = 1.0
scroll-width = 10
status-height = 25
tab-close-button = "Right"
tab-min-width = 100
tab-separator-height = "Content"
trim-search-results-whitespace = true
